### ISSUE TITLE
#BUG http-client 会将库内部错误当做http Error处理返回

### ISSUE THREAD

**Issue by bojan0624** [bluedapp/node-util-client#2]
概述
http-client 会将库内部错误当做http Error处理返回

复现步骤
1.为post请求 设置 request header 'content-type': 'application/x-www-form-urlencoded'
2.post body 数据类型为JSON
3.request lib 内部转换错误str.replace 作为 http error 500 被throw

改进方案
```javascript
     const results = await request({
        baseUrl: buildPath(host),
        url: removeBorderSlash(url),
        headers: {
          ...headers,
          'X-Request-ID': requestId,
        },
        json: true,
        ...config,
      })
```
改为使用callback， 在callback内部处理http error

https://github.com/bluedapp/node-util-client/blob/094b27c53d62370bcfe464a51a096e6b1c660bc7/packages/http-client/src/index.ts#L145

**Comment by Jiasm** [comment]
可以针对这一特殊类型的请求，手动修改 body 为字符串类型，类似 `JSON.stringify`

**Comment by bojan0624** [comment]
> 可以针对这一特殊类型的请求，手动修改 body 为字符串类型，类似 `JSON.stringify`

这只能避免这个示例问题，并不能解决 同步错误被当做http error 的错误。 之后我提PR。
